openapi: 3.0.0
info:
  title: E-Commerce Authentication API
  version: "1.0"
  description: API documentation for user authentication.
paths:
  /api/auth/login:
    post:
      summary: Log in a user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address
                password:
                  type: string
                  description: The user's password
              required:
                - email
                - password
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authenticated sessions
        401:
          description: Unauthorized - Invalid credentials
        400:
          description: Bad request - Missing email or password
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          description: The user's email address
        password:
          type: string
          description: The user's password
      required:
        - email
        - password
