openapi: 3.0.0
info:
  title: E-Commerce Order API
  version: "1.0"
  description: API documentation for managing orders.
security:
  - bearerAuth: []  # Apply Bearer token authorization globally
paths:
  /api/orders:
    get:
      summary: Retrieve orders by user ID
      tags: [Orders]
      security:
        - bearerAuth: []  # Require authorization for this endpoint
      responses:
        200:
          description: Orders retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        401:
          description: Unauthorized
        404:
          description: No orders found for this user
    post:
      summary: Create a new order
      tags: [Orders]
      security:
        - bearerAuth: []  # Require authorization for this endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        201:
          description: Order created successfully
        400:
          description: Bad request
        401:
          description: Unauthorized
  /api/orders/{id}:
    get:
      summary: Retrieve an order by ID
      tags: [Orders]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The order ID
      responses:
        200:
          description: Order data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Order not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Order:
      type: object
      properties:
        user:
          type: string
          description: The ID of the user owning the order (ObjectId)
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: The ID of the product (ObjectId)
              quantity:
                type: integer
                description: The quantity of the product ordered
        total:
          type: number
          format: float
          description: The total amount for the order
        status:
          type: string
          description: The status of the order
          default: 'Pending'
      required:
        - user
        - products
        - total
