openapi: 3.0.0
info:
  title: E-Commerce Product API
  version: "1.0"
  description: API documentation for managing products.
paths:
  /api/products:
    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: Product created successfully
        400:
          description: Bad request
    get:
      summary: Retrieve all products
      tags: [Products]
      responses:
        200:
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /api/products/{id}:
    get:
      summary: Retrieve a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        200:
          description: Product data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product not found
    put:
      summary: Update a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Product updated successfully
        400:
          description: Bad request
        404:
          description: Product not found
    delete:
      summary: Delete a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          description: The name of the product
        description:
          type: string
          description: A description of the product
        price:
          type: number
          format: float
          description: The price of the product
        stock:
          type: integer
          description: The stock quantity of the product
          default: 0
      required:
        - name
        - price
